name: "Project Bedrock CI/CD"

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  terraform:
    name: "Terraform Lint and Validate"
    runs-on: ubuntu-latest
    
    # Setting up AWS credentials securely using secrets managed in Github
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Terraform Engine
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Code Formatting Check
        run: terraform fmt -check

      - name: Initialize Workspace
        run: terraform init -backend=false

      - name: Syntactical Validation
        run: terraform validate
